# Generated by Django 5.1.6 on 2025-03-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_chatmessage_mood_chatmessage_mood_confidence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='journalentry',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(blank=True, default='No content', max_length=100),
            preserve_default=False,
        ),
    ]
