# Generated by Django 5.1.6 on 2025-04-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_message_session_chatmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psychiatrist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=8)),
                ('contact', models.CharField(max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='psychiatrists/')),
            ],
        ),
    ]
