# Generated by Django 5.1.6 on 2025-04-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_psychiatrist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='mood',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='category',
            field=models.CharField(choices=[('thought_dump', 'Thought Dump'), ('gratitude', 'Gratitude Journal'), ('mood_reflection', 'Mood Reflection'), ('goals', 'Goals & Progress'), ('daily_recap', 'Daily Recap'), ('stress_log', 'Stress Log'), ('dream_log', 'Dream Log')], default='thought_dump', max_length=30),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='emotion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
