# Generated by Django 5.1.6 on 2026-09-17 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('content', models.TextField(blank=True, help_text='Full article content if published directly on ACROCARE')),
                ('link', models.URLField(blank=True, help_text='Original external article link if scraped', max_length=500, null=True)),
                ('category', models.CharField(default='General', max_length=100)),
                ('source', models.CharField(default='ACROCARE Editorial', max_length=150)),
                ('read_time', models.CharField(default='3 min read', max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
