# Generated by Django 5.1.6 on 2025-03-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='blog',
            name='link',
            field=models.URLField(default='No summary yet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
