# Generated by Django 5.1.6 on 2025-04-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_image_blog_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image_url',
        ),
        migrations.AddField(
            model_name='blog',
            name='image_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
