# Generated by Django 5.1.6 on 2026-09-16 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blog_image_url_blog_image_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True, help_text='Full article content if published directly on ACROCARE'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='read_time',
            field=models.CharField(default='3 min read', max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='source',
            field=models.CharField(default='ACROCARE Editorial', max_length=150),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.URLField(blank=True, help_text='Original external article link if scraped', max_length=500, null=True),
        ),
    ]
