# Generated by Django 5.1.6 on 2026-09-16 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_options_blog_author_blog_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='views',
        ),
    ]
